### ISSUE TITLE
Отсутствует connection к базе данных

### ISSUE THREAD

**Issue by vlad-mp-31-17** [OpgUnity/ComputerStore#24]
**Описание бага**
При попытке подключения к базе данных вылетает ошибка 

**Как воспроизвести**
1) Развернуть сервер командой npm run start-server
2) Попробовать перейти на любой из маршрутов, определенных в роутере
3) Получить ошибку в браузере и в консоли

**Ожидаемое поведение**
Запрос отработал, вернулся jason содержащий данные из таблицы

**Полученный результат**
Ошибка в консоли и в браузере 

**Скриншоты**
![image](https://user-images.githubusercontent.com/67017075/85457519-d0c62080-b5a8-11ea-910e-835a0d6f992c.png)
![image](https://user-images.githubusercontent.com/67017075/85457531-d3287a80-b5a8-11ea-9983-72f33e2be27d.png)
![image](https://user-images.githubusercontent.com/67017075/85458033-5944c100-b5a9-11ea-892d-d043459c1532.png)

**Информация о системе**
 - ОС Windows 10
 - Браузер Yandex browser
 - Версия 20.6.1.148 (64-bit)

**Comment by BOD9ITEJI** [comment]
### Решение
Пофиксил ошибку в конфигурационном файле pg_hba.conf
